In [2]:
import pandas as pd
import numpy as np
import math

In [3]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from scipy.stats import pearsonr
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import RandomizedLasso
from sklearn.feature_selection import RFE

In [4]:
train_data = pd.read_csv('train_data_1130.csv',header=0) #多段划分 使用100m的数据训练
X = train_data.drop('label',axis=1)
y = train_data['label']
print X.shape,y.shape

(200, 90) (200,)


In [16]:
s1 = SelectKBest(chi2).fit(X,y).scores_
s1[np.isnan(s1)]=0
s1=s1.reshape(-1,1)
s1=MinMaxScaler().fit_transform(s1)
s1=map(lambda x:round(x,4),s1)
s1=np.array(s1)
s1
#MinMaxScaler().fit_transform(s1)

array([  2.80000000e-03,   2.23000000e-02,   6.40000000e-02,
         1.16700000e-01,   8.33000000e-02,   9.24000000e-02,
         1.22700000e-01,   7.83000000e-02,   7.34000000e-02,
         5.65000000e-02,   4.82000000e-02,   3.93000000e-02,
         5.85000000e-02,   3.39000000e-02,   3.95000000e-02,
         5.22000000e-02,   9.24000000e-02,   1.58000000e-01,
         2.69300000e-01,   2.59300000e-01,   3.55600000e-01,
         3.82400000e-01,   3.55600000e-01,   7.06000000e-02,
         6.40000000e-02,   6.22000000e-02,   5.36000000e-02,
         6.54000000e-02,   5.09000000e-02,   5.36000000e-02,
         5.00000000e-04,   4.30000000e-03,   1.73000000e-02,
         5.50000000e-03,   1.97000000e-02,   1.25000000e-02,
         2.87000000e-02,   7.00000000e-03,   7.10000000e-03,
         1.25000000e-02,   1.28000000e-02,   4.30000000e-03,
         4.90000000e-03,   1.25000000e-02,   1.40000000e-03,
         4.30000000e-03,   9.50000000e-03,   1.37000000e-02,
         2.87000000e-02,

In [13]:
s1 = SelectKBest(chi2).fit(X,y).scores_
s1[np.isnan(s1)]=0
s1=s1.reshape(-1,1)
s1

array([[  1.11111111e-01],
       [  8.92781316e-01],
       [  2.56060606e+00],
       [  4.66666667e+00],
       [  3.33333333e+00],
       [  3.69553073e+00],
       [  4.90909091e+00],
       [  3.13221601e+00],
       [  2.93632959e+00],
       [  2.26082863e+00],
       [  1.92857143e+00],
       [  1.57397004e+00],
       [  2.34146341e+00],
       [  1.35561497e+00],
       [  1.58064516e+00],
       [  2.08695652e+00],
       [  3.69553073e+00],
       [  6.32080925e+00],
       [  1.07701863e+01],
       [  1.03712121e+01],
       [  1.42222222e+01],
       [  1.52965686e+01],
       [  1.42222222e+01],
       [  2.82558140e+00],
       [  2.56060606e+00],
       [  2.48987109e+00],
       [  2.14525140e+00],
       [  2.61545624e+00],
       [  2.03406998e+00],
       [  2.14525140e+00],
       [  2.19298246e-02],
       [  1.70138889e-01],
       [  6.91358025e-01],
       [  2.21070812e-01],
       [  7.89473684e-01],
       [  5.00000000e-01],
       [  1.14893617e+00],
 

In [144]:
# 皮尔森系数
s2 = X.apply(lambda x:abs(pearsonr(x,y)[0])).values
s2[np.isnan(s2)]=0
s2=MinMaxScaler().fit_transform(s2)
s2=map(lambda x:round(x,4),s2)
s2=np.array(s2)
s2

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([ 0.0882,  0.2696,  0.6111,  0.8083,  0.7638,  0.7848,  0.8461,
        0.7225,  0.6835,  0.5865,  0.5196,  0.5004,  0.4771,  0.6041,
        0.6286,  0.6757,  0.7848,  0.9052,  0.9831,  0.5693,  0.631 ,
        0.6369,  0.631 ,  0.5943,  0.6111,  0.6772,  0.5979,  0.6602,
        0.6121,  0.5979,  0.0876,  0.2728,  0.469 ,  0.3325,  0.5257,
        0.4677,  0.5789,  0.403 ,  0.3015,  0.4677,  0.3718,  0.2728,
        0.2628,  0.4677,  0.1791,  0.2728,  0.4364,  0.438 ,  0.5789,
        0.0217,  0.1377,  0.1193,  0.3358,  0.3325,  0.4974,  0.0546,
        0.3669,  0.3325,  0.3703,  0.4492,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.1083,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.0314,  0.2828,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  1.    ,  0.1083,  0.1083,  0.    ,  0.1885])

In [6]:
s6 = SelectFromModel(LogisticRegression(penalty="l2", C=1)).fit(X, y)
l2 = s6.estimator_
s3=abs(l2.coef_[0])
s3=MinMaxScaler().fit_transform(s3)
s3=map(lambda x:round(x,4),s3)
s3=np.array(s3)
s3

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.78995439  0.41212329  0.26545276  0.46479158  0.30782206  0.41813819
  0.48788684  0.35053049  0.32995304  0.21086054  0.0465175   0.16911307
  0.26876107  0.04250597  0.02060322  0.15039102  0.69641035  0.89162977
  3.02819342  1.62546652  0.80651363  0.08486005  0.43352297  0.30820679
  0.17305429  0.51142875  0.14165941  0.21292183  0.07931323  0.20563814
  0.36502737  0.16162203  0.03835089  0.12695959  0.06482746  0.02113991
  0.07678272  0.04306827  0.28911109  0.09050184  0.30318013  0.70394318
  0.5065673   0.09481577  0.51935175  0.17108932  0.05206749  0.01104061
  0.3374963   0.54547717  0.27055837  0.15820934  0.86046533  0.0031916
  0.24685405  0.51083226  0.27961774  0.43564851  0.36459718  0.05369689
  0.          0.          0.          0.          0.          0.11303391
  0.          0.          0.          0.          0.          0.          0.
  0.          0.32517952  0.37074624  0.          0.          0.          0.
  0.          0.          0.          0.          0.          2.2777579
  0.06509368  0.12778401  0.          0.9979829 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [119]:
s = SelectFromModel(LogisticRegression(penalty="l1", C=1)).fit(X, y)
l1 = s.estimator_
s4=abs(l1.coef_[0])
s4=MinMaxScaler().fit_transform(s4)
s4=map(lambda x:round(x,4),s4)
s4=np.array(s4)
s4

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([ 0.1985,  0.    ,  0.    ,  0.0997,  0.    ,  0.    ,  0.2421,
        0.0522,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.1381,  1.    ,  0.5894,  0.1447,
        0.    ,  0.    ,  0.    ,  0.    ,  0.1053,  0.    ,  0.    ,
        0.    ,  0.    ,  0.0266,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.2439,
        0.    ,  0.    ,  0.0592,  0.    ,  0.    ,  0.    ,  0.    ,
        0.0792,  0.    ,  0.0487,  0.336 ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.0277,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.6971,  0.    ,  0.    ,  0.    ,  0.2158])

In [7]:
s =SelectFromModel(GradientBoostingClassifier()).fit(X, y)
gb = s.estimator_
s5=gb.feature_importances_
s5=MinMaxScaler().fit_transform(s5)
s5=map(lambda x:round(x,4),s5)
s5=np.array(s5)
s5

ValueError: Expected 2D array, got 1D array instead:
array=[  4.56259589e-02   2.97639502e-03   0.00000000e+00   1.48204852e-02
   4.17749780e-03   2.25578075e-03   2.76229142e-02   1.11634070e-02
   0.00000000e+00   5.01348943e-04   0.00000000e+00   6.23299141e-03
   4.34643143e-04   7.34109440e-04   2.18560601e-03   0.00000000e+00
   7.56600759e-05   3.89251620e-02   8.07413126e-02   1.10324582e-01
   6.35591686e-02   8.01576081e-02   7.16216037e-02   2.43368670e-03
   2.25594184e-02   9.52018236e-03   2.54520940e-03   7.29831160e-04
   0.00000000e+00   1.50241597e-03   3.02054130e-03   0.00000000e+00
   0.00000000e+00   0.00000000e+00   8.28931422e-05   0.00000000e+00
   0.00000000e+00   1.91735459e-04   1.17025090e-03   0.00000000e+00
   1.12467944e-03   2.34398037e-02   0.00000000e+00   0.00000000e+00
   1.19493168e-02   4.55624009e-04   0.00000000e+00   0.00000000e+00
   0.00000000e+00   2.20698739e-02   1.80274271e-02   2.95582741e-03
   5.68678737e-02   0.00000000e+00   1.95780874e-02   0.00000000e+00
   4.95457967e-04   1.41002819e-02   7.67010636e-03   1.70123457e-03
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   2.80026310e-02   2.15351159e-02
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   1.00921324e-01   0.00000000e+00   0.00000000e+00
   0.00000000e+00   6.12129352e-02].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [121]:
s =SelectFromModel(RandomForestRegressor()).fit(X, y)
rf = s.estimator_
s6=rf.feature_importances_
s6=MinMaxScaler().fit_transform(s6)
s6=map(lambda x:round(x,4),s6)
s6=np.array(s6)
s6

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([  1.65500000e-01,   4.00000000e-04,   9.50000000e-03,
         1.50800000e-01,   1.40000000e-02,   0.00000000e+00,
         1.00400000e-01,   9.60000000e-03,   0.00000000e+00,
         9.50000000e-03,   0.00000000e+00,   4.50000000e-03,
         6.40000000e-03,   1.46000000e-02,   0.00000000e+00,
         7.70000000e-03,   3.70000000e-03,   1.95300000e-01,
         9.11700000e-01,   7.69900000e-01,   2.98100000e-01,
         5.43000000e-02,   8.03000000e-02,   1.37000000e-02,
         3.25000000e-02,   1.13700000e-01,   1.85000000e-02,
         0.00000000e+00,   0.00000000e+00,   1.17000000e-02,
         6.70000000e-03,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   1.00000000e-04,   2.87000000e-02,
         0.00000000e+00,   2.80000000e-02,   1.03800000e-01,
         7.70000000e-03,   0.00000000e+00,   1.41000000e-02,
         1.00000000e-04,   0.00000000e+00,   0.00000000e+00,
         1.56000000e-02,

In [122]:
rlasso = RandomizedLasso()  # 默认通过AIC选择正则化系数alpha
rlasso.fit(X, y)
s7=rlasso.scores_
s7=MinMaxScaler().fit_transform(s7)
s7=map(lambda x:round(x,4),s7)
s7=np.array(s7)
s7

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:356: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([ 0.3  ,  0.1  ,  0.18 ,  0.39 ,  0.085,  0.465,  0.365,  0.305,
        0.22 ,  0.125,  0.   ,  0.   ,  0.005,  0.   ,  0.   ,  0.005,
        0.165,  0.555,  1.   ,  0.99 ,  0.795,  0.405,  0.59 ,  0.115,
        0.04 ,  0.305,  0.03 ,  0.07 ,  0.005,  0.025,  0.075,  0.   ,
        0.05 ,  0.015,  0.03 ,  0.155,  0.005,  0.02 ,  0.005,  0.   ,
        0.1  ,  0.055,  0.125,  0.   ,  0.125,  0.   ,  0.005,  0.015,
        0.065,  0.26 ,  0.005,  0.175,  0.39 ,  0.015,  0.34 ,  0.015,
        0.   ,  0.   ,  0.   ,  0.01 ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.185,  0.355,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.115,
        0.   ,  0.68 ])

In [123]:
lr = LogisticRegression(penalty='l1')
#rank all features, i.e continue the elimination until the last one
rfe = RFE(lr, n_features_to_select=1)
rfe.fit(X,y)
s8=rfe.ranking_
n=len(s8)
s8=map(lambda x:round((n+1-x)/float(n),4),s8)
s8=np.array(s8)
s8

array([ 0.9333,  0.7333,  0.7444,  0.8778,  0.7556,  0.7667,  0.9556,
        0.8333,  0.7   ,  0.6667,  0.6778,  0.6556,  0.6333,  0.5667,
        0.5556,  0.6111,  0.5444,  0.9111,  0.9889,  0.9778,  0.9   ,
        0.4333,  0.4111,  0.3889,  0.3778,  0.8889,  0.3222,  0.3   ,
        0.2778,  0.2667,  0.8111,  0.2111,  0.1889,  0.1667,  0.1444,
        0.1222,  0.1   ,  0.0778,  0.0556,  0.0333,  0.0111,  0.9444,
        0.3667,  0.2556,  0.8556,  0.0222,  0.0444,  0.0667,  0.0889,
        0.8667,  0.7222,  0.8444,  0.9667,  0.6444,  0.6222,  0.6   ,
        0.5889,  0.8222,  0.5333,  0.5222,  0.7889,  0.7111,  0.6889,
        0.5778,  0.4667,  0.4556,  0.4444,  0.4222,  0.4   ,  0.3556,
        0.3444,  0.3333,  0.3111,  0.2889,  0.2444,  0.2333,  0.4778,
        0.5111,  0.2222,  0.2   ,  0.1778,  0.1556,  0.1333,  0.1111,
        0.4889,  1.    ,  0.5   ,  0.7778,  0.8   ,  0.9222])

In [145]:
s=s1+s2+s3+s4+s5+s6+s7+s8
s

array([ 2.3673,  1.2887,  1.6967,  2.7755,  1.8391,  2.263 ,  3.0457,
        2.2179,  1.7928,  1.5193,  1.2655,  1.2834,  1.273 ,  1.2333,
        1.2691,  1.4025,  1.8608,  3.4397,  6.886 ,  5.6925,  3.9786,
        2.4089,  3.127 ,  1.3171,  1.387 ,  2.3876,  1.0818,  1.1659,
        0.972 ,  1.0293,  1.1554,  0.557 ,  0.7379,  0.5616,  0.7417,
        0.7644,  0.738 ,  0.5238,  0.504 ,  0.5434,  0.634 ,  2.0692,
        0.9344,  0.7671,  1.5142,  0.3583,  0.5125,  0.537 ,  0.8886,
        1.6447,  1.1271,  1.3013,  3.0289,  0.9988,  1.7713,  0.8417,
        1.0529,  1.4698,  1.0911,  1.0178,  0.7889,  0.7111,  0.6889,
        0.5778,  0.4667,  0.6179,  0.4444,  0.4222,  0.4   ,  0.3556,
        0.3444,  0.3333,  0.3111,  0.2889,  0.9556,  1.3013,  0.4778,
        0.5111,  0.2222,  0.2   ,  0.1778,  0.1556,  0.1333,  0.1111,
        0.4889,  7.3641,  0.6465,  1.06  ,  0.8   ,  3.0928])

In [146]:
s_sum = pd.Series(s,index=X.columns)
s_sum.sort_values(ascending=False,inplace=True)
s_sum

psd_cha_25     7.3641
psd_mean_25    6.8860
psd_mean_26    5.6925
psd_mean_27    3.9786
psd_mean_24    3.4397
psd_mean_29    3.1270
psd_cha_29     3.0928
psd_mean_14    3.0457
psd_var_29     3.0289
psd_mean_11    2.7755
psd_mean_28    2.4089
psd_mean_5     2.3876
psd_mean_0     2.3673
psd_mean_13    2.2630
psd_mean_15    2.2179
psd_var_19     2.0692
psd_mean_23    1.8608
psd_mean_12    1.8391
psd_mean_16    1.7928
psd_var_4      1.7713
psd_mean_10    1.6967
psd_var_26     1.6447
psd_mean_17    1.5193
psd_var_21     1.5142
psd_var_7      1.4698
psd_mean_22    1.4025
psd_mean_4     1.3870
psd_mean_3     1.3171
psd_cha_15     1.3013
psd_var_28     1.3013
                ...  
psd_cha_26     0.6465
psd_var_18     0.6340
psd_cha_5      0.6179
psd_cha_3      0.5778
psd_var_11     0.5616
psd_var_1      0.5570
psd_var_17     0.5434
psd_var_24     0.5370
psd_var_15     0.5238
psd_var_23     0.5125
psd_cha_17     0.5111
psd_var_16     0.5040
psd_cha_24     0.4889
psd_cha_16     0.4778
psd_cha_4 

In [135]:
a=s_sum.index.values

In [140]:
b=list(a)

In [141]:
del b[0]

In [142]:
b

['psd_mean_25',
 'psd_mean_26',
 'psd_mean_27',
 'psd_cha_29',
 'psd_var_29',
 'psd_mean_24',
 'psd_mean_29',
 'psd_mean_0',
 'psd_mean_14',
 'psd_mean_11',
 'psd_var_19',
 'psd_mean_5',
 'psd_var_26',
 'psd_mean_28',
 'psd_mean_13',
 'psd_mean_15',
 'psd_var_21',
 'psd_var_4',
 'psd_mean_23',
 'psd_var_7',
 'psd_var_28',
 'psd_mean_16',
 'psd_var_0',
 'psd_mean_12',
 'psd_mean_10',
 'psd_mean_1',
 'psd_cha_15',
 'psd_var_27',
 'psd_cha_14',
 'psd_mean_17',
 'psd_cha_27',
 'psd_var_5',
 'psd_mean_2',
 'psd_var_8',
 'psd_var_2',
 'psd_mean_19',
 'psd_mean_4',
 'psd_mean_3',
 'psd_cha_28',
 'psd_cha_0',
 'psd_var_6',
 'psd_mean_22',
 'psd_mean_18',
 'psd_cha_1',
 'psd_cha_2',
 'psd_var_3',
 'psd_mean_21',
 'psd_mean_20',
 'psd_var_9',
 'psd_cha_3',
 'psd_mean_7',
 'psd_cha_26',
 'psd_cha_5',
 'psd_mean_6',
 'psd_cha_17',
 'psd_mean_9',
 'psd_cha_24',
 'psd_cha_16',
 'psd_cha_4',
 'psd_cha_6',
 'psd_cha_7',
 'psd_var_25',
 'psd_cha_8',
 'psd_mean_8',
 'psd_var_18',
 'psd_cha_9',
 'psd_cha

In [143]:
X[b]

psd_mean_25  psd_mean_26  psd_mean_27  psd_cha_29  psd_var_29  \
0              1            1            1           1           1   
1              1            1            0           0           1   
2              1            1            1           0           1   
3              1            1            0           0           1   
4              1            1            1           1           1   
5              1            1            1           0           1   
6              1            1            0           0           1   
7              1            1            0           0           1   
8              1            1            0           0           1   
9              1            1            1           1           1   
10             1            1            0           0           1   
11             1            1            0           0           1   
12             1            1            0           0           1   
13             1            1            1           0           1   
14             1            1            0           0           1   
15             1            1            0           0           0   
16             1            1            0           0           0   
17             1            1            0           0           1   
18             1            1            0           0           0   
19             1            1            0           0           1   
20             1            0            0           0           0   
21             1            0            0           0           1   
22             1            0            1           0           1   
23             1            1            1           0           0   
24             1            0            0           0           1   
25             1            0            1           0           1   
26             1            1            1           0           1   
27             1            0            1           0           1   
28             1            1            1           0           1   
29             1            0            0           0           1   
..           ...          ...          ...         ...         ...   
170            0            0            0           0           1   
171            0            1            1           0           0   
172            0            0            0           0           1   
173            1            1            1           0           1   
174            0            0            0           0           1   
175            0            0            0           0           0   
176            0            0            0           0           1   
177            0            0            0           0           1   
178            0            0            0           0           1   
179            0            0            0           0           0   
180            1            1            1           0           1   
181            1            1            1           0           1   
182            1            1            1           0           1   
183            1            1            1           0           1   
184            1            1            1           0           1   
185            1            1            1           0           1   
186            1            1            1           0           1   
187            1            1            1           0           1   
188            1            1            1           0           1   
189            1            1            1           0           1   
190            0            0            1           0           1   
191            0            1            1           0           1   
192            1            1            1           0           1   
193            0            0            1           0           1   
194            0            1            0           0           1   
195            

In [11]:
# 递归特征消除（REF）
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

names = X.columns
#use linear regression as the model
lr = LogisticRegression(penalty='l2')
#rank all features, i.e continue the elimination until the last one
rfe = RFE(lr, n_features_to_select=1)
rfe.fit(X,y)

print "Features sorted by their rank:"
print sorted(zip(map(lambda x: round(x, 4), rfe.ranking_), names))

Features sorted by their rank:
[(1.0, 'psd_cha_25'), (2.0, 'psd_mean_25'), (3.0, 'psd_mean_26'), (4.0, 'psd_mean_24'), (5.0, 'psd_var_29'), (6.0, 'psd_mean_14'), (7.0, 'psd_var_19'), (8.0, 'psd_mean_27'), (9.0, 'psd_cha_29'), (10.0, 'psd_mean_0'), (11.0, 'psd_mean_5'), (12.0, 'psd_var_21'), (13.0, 'psd_mean_15'), (14.0, 'psd_var_2'), (15.0, 'psd_mean_11'), (16.0, 'psd_mean_23'), (17.0, 'psd_var_5'), (18.0, 'psd_var_26'), (19.0, 'psd_mean_13'), (20.0, 'psd_var_7'), (21.0, 'psd_mean_16'), (22.0, 'psd_mean_29'), (23.0, 'psd_var_0'), (24.0, 'psd_cha_15'), (25.0, 'psd_mean_12'), (26.0, 'psd_var_8'), (27.0, 'psd_var_25'), (28.0, 'psd_var_18'), (29.0, 'psd_mean_10'), (30.0, 'psd_cha_14'), (31.0, 'psd_mean_3'), (32.0, 'psd_mean_1'), (33.0, 'psd_mean_2'), (34.0, 'psd_var_6'), (35.0, 'psd_var_27'), (36.0, 'psd_var_16'), (37.0, 'psd_mean_7'), (38.0, 'psd_mean_17'), (39.0, 'psd_mean_9'), (40.0, 'psd_var_4'), (41.0, 'psd_var_22'), (42.0, 'psd_var_1'), (43.0, 'psd_mean_4'), (44.0, 'psd_mean_19'), (4

In [12]:
# 递归特征消除（REF）
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

names = X.columns
#use linear regression as the model
lr = LogisticRegression(penalty='l1')
#rank all features, i.e continue the elimination until the last one
rfe = RFE(lr, n_features_to_select=1)
rfe.fit(X,y)

print "Features sorted by their rank:"
print sorted(zip(map(lambda x: round(x, 4), rfe.ranking_), names))

Features sorted by their rank:
[(1.0, 'psd_cha_25'), (2.0, 'psd_mean_25'), (3.0, 'psd_mean_26'), (4.0, 'psd_var_29'), (5.0, 'psd_mean_14'), (6.0, 'psd_var_19'), (7.0, 'psd_mean_0'), (8.0, 'psd_cha_29'), (9.0, 'psd_mean_24'), (10.0, 'psd_mean_27'), (11.0, 'psd_mean_5'), (12.0, 'psd_mean_11'), (13.0, 'psd_var_26'), (14.0, 'psd_var_21'), (15.0, 'psd_var_28'), (16.0, 'psd_mean_15'), (17.0, 'psd_var_7'), (18.0, 'psd_var_0'), (19.0, 'psd_cha_28'), (20.0, 'psd_cha_0'), (21.0, 'psd_cha_27'), (22.0, 'psd_mean_13'), (23.0, 'psd_mean_12'), (24.0, 'psd_mean_10'), (25.0, 'psd_mean_1'), (26.0, 'psd_var_27'), (27.0, 'psd_cha_1'), (28.0, 'psd_mean_16'), (29.0, 'psd_cha_2'), (30.0, 'psd_mean_18'), (31.0, 'psd_mean_17'), (32.0, 'psd_mean_19'), (33.0, 'psd_var_3'), (34.0, 'psd_mean_2'), (35.0, 'psd_var_4'), (36.0, 'psd_mean_20'), (37.0, 'psd_var_5'), (38.0, 'psd_var_6'), (39.0, 'psd_cha_3'), (40.0, 'psd_mean_22'), (41.0, 'psd_mean_21'), (42.0, 'psd_mean_23'), (43.0, 'psd_var_8'), (44.0, 'psd_var_9'), (45

In [15]:
# 递归特征消除（REF）
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

names = X.columns
#use linear regression as the model
s = SVR(kernel="linear")
#rank all features, i.e continue the elimination until the last one
rfe = RFE(s, n_features_to_select=1)
rfe.fit(X,y)

print "Features sorted by their rank:"
print sorted(zip(map(lambda x: round(x, 4), rfe.ranking_), names))

Features sorted by their rank:
[(1.0, 'psd_cha_25'), (2.0, 'psd_var_2'), (3.0, 'psd_mean_25'), (4.0, 'psd_mean_21'), (5.0, 'psd_var_28'), (6.0, 'psd_mean_22'), (7.0, 'psd_cha_1'), (8.0, 'psd_var_8'), (9.0, 'psd_cha_7'), (10.0, 'psd_cha_0'), (11.0, 'psd_var_3'), (12.0, 'psd_var_22'), (13.0, 'psd_var_23'), (14.0, 'psd_mean_20'), (15.0, 'psd_mean_4'), (16.0, 'psd_var_21'), (17.0, 'psd_var_18'), (18.0, 'psd_var_20'), (19.0, 'psd_var_25'), (20.0, 'psd_var_12'), (21.0, 'psd_var_19'), (22.0, 'psd_cha_2'), (23.0, 'psd_cha_20'), (24.0, 'psd_var_17'), (25.0, 'psd_mean_10'), (26.0, 'psd_cha_21'), (27.0, 'psd_mean_18'), (28.0, 'psd_var_6'), (29.0, 'psd_cha_3'), (30.0, 'psd_cha_18'), (31.0, 'psd_cha_5'), (32.0, 'psd_mean_19'), (33.0, 'psd_var_11'), (34.0, 'psd_mean_7'), (35.0, 'psd_var_4'), (36.0, 'psd_cha_11'), (37.0, 'psd_cha_6'), (38.0, 'psd_cha_16'), (39.0, 'psd_cha_28'), (40.0, 'psd_cha_4'), (41.0, 'psd_var_16'), (42.0, 'psd_cha_15'), (43.0, 'psd_cha_12'), (44.0, 'psd_cha_19'), (45.0, 'psd_var