In [1]:
# 使用0925_1训练数据训练得到学习器（SVM），结果可识别全部已测数据  注：不同模型结果都一样！
import pandas as pd
import numpy as np
import math
from sklearn.svm import SVC

In [17]:
train_data = pd.read_csv('train_data_1205.csv',header=0) #全部数据中的训练部分
test_data = pd.read_csv('test_data_1205_1.csv',header=0) #全部数据中的测试部分
X_train = train_data.drop('label',axis=1)
y_train = train_data['label']
X_test = test_data.drop('label',axis=1)
y_test = test_data['label']
print X_train.shape,y_train.shape,X_test.shape,y_test.shape

(120, 90) (120,) (125, 90) (125,)


In [18]:
#特征选择
#X_train_s = X_train[['psd_cha_25','psd_var_2','psd_mean_25','psd_mean_21','psd_var_28']]
#X_train_s = X_train[['psd_cha_25','psd_var_2','psd_mean_25','psd_mean_2','psd_var_8']]
X_train_s = X_train[['psd_cha_25','psd_mean_25','psd_mean_26','psd_var_29','psd_mean_14','psd_mean_0','psd_mean_15','psd_var_21']]
#X_train_s = X_train[['psd_cha_25','psd_mean_25']]
X_train_s.shape

(120, 8)

In [19]:
X_test_s = X_test[['psd_cha_25','psd_mean_25','psd_mean_26','psd_var_29','psd_mean_14','psd_mean_0','psd_mean_15','psd_var_21']]

In [34]:
#模型选择
from sklearn.model_selection import cross_val_score
clf = SVC(kernel='linear', C=10)
scores = cross_val_score(clf, X_train_s, y_train, scoring='roc_auc',cv=10) #5-fold cross validation
print scores,scores.mean() 

[ 0.875       0.75        0.79166667  0.66666667  0.9375      0.54166667
  0.5         0.5         0.83333333  0.875     ] 0.727083333333


In [117]:
#模型选择
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score
clf = AdaBoostClassifier(n_estimators=50,algorithm='SAMME.R')
scores = cross_val_score(clf, X, y, cv=5) #5-fold cross validation
scores 

array([ 1.    ,  0.875 ,  0.75  ,  0.8125,  1.    ])

In [119]:
clf.fit(X,y)
clf.score(X,y)

0.88749999999999996

In [49]:
# SVM 模型
from sklearn.model_selection import GridSearchCV
parameters={'kernel':('rbf','linear','poly','sigmoid'),'C':[0.01,0.1,1,5,10]}
svr = SVC()
clf = GridSearchCV(svr,parameters,scoring='roc_auc',cv=10)
clf.fit(X_train,y_train)
print(clf.best_estimator_)
print clf.best_score_ 

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.927083333333


In [11]:
from sklearn.model_selection import GridSearchCV
parameters={'kernel':('rbf','linear','poly','sigmoid'),'C':[0.0000001,0.001,0.01,0.1,1,5,10,20]}
svr = SVC()
clf = GridSearchCV(svr,parameters,scoring='accuracy',cv=5)
clf.fit(X_train_s,y_train)
print(clf.best_estimator_)
print clf.best_score_ 

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.958333333333


In [18]:
# LR  模型
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
parameters={'C':[0.001,0.01,0.1,1,5,10,20]}
lr = LogisticRegression()
clf = GridSearchCV(lr,parameters,scoring='roc_auc',cv=10)
clf.fit(X_train,y_train)
print(clf.best_estimator_)
print clf.best_score_ 

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
1.0


In [20]:
# LR  模型
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
parameters={'C':[0.0000001,0.001,0.01,0.1,0.5,1,5,10,20]}
lr = LogisticRegression()
clf = GridSearchCV(lr,parameters,scoring='accuracy',cv=10)
clf.fit(X_train_s,y_train)
print(clf.best_estimator_)
print clf.best_score_

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
0.933333333333


In [21]:
clf_train = clf.best_estimator_
#clf_train.score(X_test_s,y_test)

In [22]:
clf_train.predict(X_test_s)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
y_test.values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [132]:
#predict
#path_predict = './0908/NO/GL/2455/NO_SA_2455_20_5000_00'
#path_predict = './0908/TC/GL/140/2425/TC_SA_2425_140_20_5000_00'
#path_predict = './0711/N/SA/SA2405/SA00'
path_predict = './0711/Y/gong/SA/SA2415-80/SA00'
n = 400
x_predict = get_real_data(path_predict)
#x_predict_samp = x_predict[range(0,5000,5)]
#x = x_predict.values
y_predict = clf.predict(x_predict)
print y_predict

[1 0 0 1 1]


In [39]:
x_predict

array([ 1.,  1.,  1., ..., -1., -1., -1.])

In [48]:
len(x_predict)

3000

In [19]:
len(x_predict)

10001

In [57]:
path_predict = './0908/NO/GL/2475/NO_SA_2475_20_5000_00'
#path_predict = './0908/TC/GL/110/2475/TC_SA_2475_110_20_5000_00'
#path_predict = './0711/N/SA/SA2415/SA00'
#path_predict = './0711/Y/gong/SA/SA2475-80/SA00'
n = 400
x_predict = get_real_data(path_predict,n)
print x_predict.shape

(10001,)


In [41]:
a = x_predict.values

In [43]:
a[index_sel].shape

(1000,)