In [1]:
# 使用0925_1训练数据训练得到学习器（SVM），结果可识别全部已测数据  注：不同模型结果都一样！
import pandas as pd
import numpy as np
import math
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [2]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from scipy.stats import pearsonr
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import RandomizedLasso
from sklearn.feature_selection import RFE

In [4]:
train_data = pd.read_csv('train_data_1221.csv',header=0) #全部数据中的训练部分
test_data = pd.read_csv('test_data_1221.csv',header=0) #全部数据中的测试部分
X_train = train_data.drop('label',axis=1)
y_train = train_data['label']
X_test = test_data.drop('label',axis=1)
y_test = test_data['label']
print X_train.shape,y_train.shape,X_test.shape,y_test.shape

(9000, 90) (9000,) (1400, 90) (1400,)


In [5]:
def feature_selection(X_train,y_train,sorted_feature,selected_feature):
	score = 0
	while sorted_feature:
		selected_feature.append(sorted_feature[0])
		del sorted_feature[0]
		score_new,clf_best = model_selection(X_train,y_train,selected_feature)
		if score_new <= score:
			selected_feature.pop()
		else:
			score = score_new
			clf = clf_best
	return selected_feature,score,clf

In [6]:
def model_selection(X_train,y_train,feature):
	parameters={'C':[0.001,0.01,0.1,1,5,10,20]}
	lr = LogisticRegression()
	clf = GridSearchCV(lr,parameters,scoring='accuracy',cv=10)
	clf.fit(X_train[feature],y_train)
	return clf.best_score_,clf.best_estimator_

In [7]:
def feature_sort(X,y):
	# 卡方
	s1 = SelectKBest(chi2).fit(X,y).scores_
	s1[np.isnan(s1)] = 0
	s1=s1.reshape(-1,1)
	s1 = MinMaxScaler().fit_transform(s1)
	s1 = map(lambda x:round(x,4),s1)
	s1 = np.array(s1)
	# 皮尔森系数
	s2 = X.apply(lambda x:abs(pearsonr(x,y)[0])).values
	s2[np.isnan(s2)]=0
	s2=s2.reshape(-1,1)
	s2 = MinMaxScaler().fit_transform(s2)
	s2 = map(lambda x:round(x,4),s2)
	s2 = np.array(s2)
	# L2正则
	s3 = SelectFromModel(LogisticRegression(penalty="l2", C=1)).fit(X, y)
	l2 = s3.estimator_
	s3 = abs(l2.coef_[0])
	s3 = s3.reshape(-1,1)
	s3 = MinMaxScaler().fit_transform(s3)
	s3 = map(lambda x:round(x,4),s3)
	s3 = np.array(s3)
	# L1正则
	s4 = SelectFromModel(LogisticRegression(penalty="l1", C=1)).fit(X, y)
	l1 = s4.estimator_
	s4 = abs(l1.coef_[0])
	s4 = s4.reshape(-1,1)
	s4 = MinMaxScaler().fit_transform(s4)
	s4 = map(lambda x:round(x,4),s4)
	s4 = np.array(s4)
	# GBDT
	s5 =SelectFromModel(GradientBoostingClassifier()).fit(X, y)
	gb = s5.estimator_
	s5 = gb.feature_importances_
	s5 = s5.reshape(-1,1)
	s5 = MinMaxScaler().fit_transform(s5)
	s5 = map(lambda x:round(x,4),s5)
	s5 = np.array(s5)
	# 随机森林
	s6 = SelectFromModel(RandomForestRegressor()).fit(X, y)
	rf = s6.estimator_
	s6 = rf.feature_importances_
	s6 = s6.reshape(-1,1)
	s6 = MinMaxScaler().fit_transform(s6)
	s6 = map(lambda x:round(x,4),s6)
	s6 = np.array(s6)
	# 稳定性
	rlasso = RandomizedLasso()  # 默认通过AIC选择正则化系数alpha
	rlasso.fit(X, y)
	s7 = rlasso.scores_
	s7 = s7.reshape(-1,1)
	s7 = MinMaxScaler().fit_transform(s7)
	s7 = map(lambda x:round(x,4),s7)
	s7 = np.array(s7)
	# REF
	lr = LogisticRegression(penalty='l1')
	rfe = RFE(lr, n_features_to_select=1)
	rfe.fit(X,y)
	s8 = rfe.ranking_
	s8 = map(lambda x:round((len(s8)+1-x)/float(len(s8)),4),s8)
	s8 = np.array(s8)
	# 总分
	s = s1+s2+s3+s4+s5+s6+s7+s8
	s_sum = pd.Series(s,index=X.columns)
	s_sum.sort_values(ascending=False,inplace=True)
	return s_sum.index

In [8]:
feature_index = feature_sort(X_train,y_train)
sorted_feature = list(feature_index.values)
sorted_feature_copy = list(sorted_feature)
selected_feature = []
feature,score,clf = feature_selection(X_train,y_train,sorted_feature,selected_feature)

/usr/local/lib/python2.7/dist-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class RandomizedLasso is deprecated; The class RandomizedLasso is deprecated in 0.19 and will be removed in 0.21.
  warnings.warn(msg, category=DeprecationWarning)


In [9]:
sorted_feature_copy

['psd_mean_16',
 'psd_mean_1',
 'psd_mean_21',
 'psd_mean_11',
 'psd_mean_7',
 'psd_mean_14',
 'psd_mean_9',
 'psd_mean_23',
 'psd_mean_10',
 'psd_mean_15',
 'psd_mean_24',
 'psd_mean_3',
 'psd_mean_17',
 'psd_mean_5',
 'psd_mean_4',
 'psd_mean_0',
 'psd_mean_13',
 'psd_mean_19',
 'psd_mean_18',
 'psd_mean_6',
 'psd_mean_2',
 'psd_mean_8',
 'psd_mean_22',
 'psd_mean_20',
 'psd_mean_12',
 'psd_var_0',
 'psd_var_11',
 'psd_var_13',
 'psd_var_9',
 'psd_cha_25',
 'psd_var_8',
 'psd_mean_25',
 'psd_var_12',
 'psd_var_17',
 'psd_var_10',
 'psd_var_19',
 'psd_var_15',
 'psd_var_5',
 'psd_var_18',
 'psd_var_3',
 'psd_var_14',
 'psd_var_24',
 'psd_var_4',
 'psd_var_21',
 'psd_var_6',
 'psd_cha_24',
 'psd_var_7',
 'psd_var_1',
 'psd_mean_26',
 'psd_var_25',
 'psd_var_16',
 'psd_var_2',
 'psd_var_20',
 'psd_var_22',
 'psd_cha_0',
 'psd_cha_13',
 'psd_var_27',
 'psd_cha_8',
 'psd_cha_6',
 'psd_var_28',
 'psd_cha_11',
 'psd_cha_29',
 'psd_cha_28',
 'psd_cha_22',
 'psd_cha_3',
 'psd_cha_18',
 'psd_c

In [10]:
feature

['psd_mean_16',
 'psd_mean_1',
 'psd_mean_21',
 'psd_mean_11',
 'psd_mean_7',
 'psd_mean_14',
 'psd_mean_9',
 'psd_mean_23',
 'psd_mean_10',
 'psd_mean_15',
 'psd_mean_24',
 'psd_mean_3',
 'psd_mean_17',
 'psd_mean_5',
 'psd_mean_4',
 'psd_mean_0',
 'psd_mean_13',
 'psd_mean_19',
 'psd_mean_18',
 'psd_mean_6',
 'psd_mean_2',
 'psd_mean_8',
 'psd_mean_22',
 'psd_mean_20',
 'psd_mean_12',
 'psd_cha_25',
 'psd_var_27',
 'psd_cha_14',
 'psd_cha_23',
 'psd_cha_2']

In [11]:
score

0.95599999999999996

In [13]:
clf.predict(X_test[feature])

array([1, 1, 1, ..., 0, 0, 0])

In [12]:
X_test=X_test[feature]

In [27]:
X_test.iloc[range(100,200),:]

psd_mean_16  psd_mean_1  psd_mean_21  psd_mean_11  psd_mean_7  \
100     0.620663    0.617262     0.627678     0.625996    0.624317   
101     0.616909    0.623628     0.623981     0.624648    0.624751   
102     0.620346    0.621194     0.630690     0.619885    0.635919   
103     0.629407    0.613060     0.626446     0.615053    0.626698   
104     0.620781    0.621571     0.622416     0.630627    0.621295   
105     0.624217    0.616583     0.623218     0.620809    0.613155   
106     0.629152    0.611841     0.625705     0.623468    0.622765   
107     0.620607    0.620344     0.623944     0.617869    0.612388   
108     0.630978    0.611078     0.623113     0.624538    0.618359   
109     0.616078    0.619133     0.635297     0.618807    0.626328   
110     0.625300    0.633927     0.623438     0.625923    0.629626   
111     0.617209    0.611659     0.624950     0.619653    0.617561   
112     0.625378    0.618031     0.628804     0.629537    0.626582   
113     0.620705    0.620233     0.624800     0.628799    0.630398   
114     0.624245    0.613165     0.628767     0.618009    0.621138   
115     0.617188    0.615042     0.615066     0.618021    0.617071   
116     0.620543    0.617725     0.610939     0.611821    0.620967   
117     0.624263    0.613485     0.626509     0.628624    0.617725   
118     0.620215    0.618284     0.627711     0.610641    0.627968   
119     0.620947    0.615958     0.627849     0.616642    0.624165   
120     0.620022    0.621971     0.631701     0.626769    0.613502   
121     0.624191    0.618709     0.621775     0.625341    0.623090   
122     0.623740    0.614494     0.626780     0.621247    0.620914   
123     0.626937    0.631732     0.623274     0.634673    0.622742   
124     0.622165    0.613101     0.621761     0.623022    0.619885   
125     0.621898    0.627676     0.628844     0.611272    0.620461   
126     0.623767    0.616640     0.618809     0.624786    0.617233   
127     0.626653    0.622679     0.632834     0.620034    0.629626   
128     0.618758    0.627990     0.624073     0.621238    0.619809   
129     0.618047    0.625442     0.629405     0.629485    0.615725   
..           ...         ...          ...          ...         ...   
170     0.624354    0.620633     0.617418     0.621555    0.620436   
171     0.622165    0.622488     0.626552     0.615128    0.625313   
172     0.628901    0.610156     0.620934     0.621319    0.624065   
173     0.612091    0.627694     0.622485     0.621205    0.632271   
174     0.610566    0.619414     0.631171     0.616566    0.621697   
175     0.611384    0.622408     0.628306     0.621851    0.623597   
176     0.622708    0.614430     0.624557     0.612168    0.629054   
177     0.620992    0.618234     0.615778     0.624520    0.619481   
178     0.616750    0.620384     0.626243     0.622139    0.613528   
179     0.620449    0.617848     0.629107     0.616011    0.626387   
180     0.616699    0.628226     0.623499     0.616841    0.615188   
181     0.617523    0.623887     0.632848     0.621758    0.611365   
182     0.617075    0.616252     0.633786     0.621242    0.615403   
183     0.619330    0.615473     0.631510     0.609512    0.622819   
184     0.623134    0.615545     0.632227     0.623096    0.610627   
185     0.632572    0.622683     0.631779     0.621504    0.617797   
186     0.626341    0.619138     0.632431     0.626501    0.621828   
187     0.617845    0.614808     0.624844     0.615142    0.625744   
188     0.619575    0.625871     0.625696     0.616718    0.618562   
189     0.619101    0.614747     0.626421     0.621841    0.622809   
190     0.620028    0.627729     0.623533     0.622336    0.621636   
191     0.616049    0.625846     0.626305     0.625554    0.621554   
192     0.623892    0.625537     0.626488     0.619539    0.618210   
193     0.622222    0.624381     0.622803     0.623377    0.623646   
194     0.620749    0.624478     0.629641     0.615373    0.611456   
195     0.62044

In [19]:
clf.score(X_test.iloc[range(300,400),:],y_test.iloc[range(800,900),])

1.0

In [76]:
y_test.values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
# SVM 模型
from sklearn.model_selection import GridSearchCV
parameters={'kernel':('rbf','linear','poly','sigmoid'),'C':[0.01,0.1,1,5,10]}
svr = SVC()
clf = GridSearchCV(svr,parameters,scoring='roc_auc',cv=10)
clf.fit(X_train,y_train)
print(clf.best_estimator_)
print clf.best_score_ 

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.927083333333


In [78]:
from sklearn.model_selection import GridSearchCV
parameters={'kernel':('rbf','linear','poly','sigmoid'),'C':[0.0000001,0.001,0.01,0.1,1,5,10,20]}
svr = SVC()
clf = GridSearchCV(svr,parameters,scoring='roc_auc',cv=10)
clf.fit(X_train_s,y_train)
print(clf.best_estimator_)
print clf.best_score_ 

SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.856770833333


In [18]:
# LR  模型
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
parameters={'C':[0.001,0.01,0.1,1,5,10,20]}
lr = LogisticRegression()
clf = GridSearchCV(lr,parameters,scoring='roc_auc',cv=10)
clf.fit(X_train,y_train)
print(clf.best_estimator_)
print clf.best_score_ 

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
1.0


In [30]:
# LR  模型
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
parameters={'C':[0.0000001,0.001,0.01,0.1,0.5,1,5,10,20]}
lr = LogisticRegression()
clf = GridSearchCV(lr,parameters,scoring='accuracy',cv=10)
clf.fit(X_train_s,y_train)
print(clf.best_estimator_)
print clf.best_score_

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
0.95


In [31]:
clf_train = clf.best_estimator_
#clf_train.score(X_test_s,y_test)

In [32]:
clf_train.predict(X_test_s)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
y_test.values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [132]:
#predict
#path_predict = './0908/NO/GL/2455/NO_SA_2455_20_5000_00'
#path_predict = './0908/TC/GL/140/2425/TC_SA_2425_140_20_5000_00'
#path_predict = './0711/N/SA/SA2405/SA00'
path_predict = './0711/Y/gong/SA/SA2415-80/SA00'
n = 400
x_predict = get_real_data(path_predict)
#x_predict_samp = x_predict[range(0,5000,5)]
#x = x_predict.values
y_predict = clf.predict(x_predict)
print y_predict

[1 0 0 1 1]


In [39]:
x_predict

array([ 1.,  1.,  1., ..., -1., -1., -1.])

In [48]:
len(x_predict)

3000

In [19]:
len(x_predict)

10001

In [57]:
path_predict = './0908/NO/GL/2475/NO_SA_2475_20_5000_00'
#path_predict = './0908/TC/GL/110/2475/TC_SA_2475_110_20_5000_00'
#path_predict = './0711/N/SA/SA2415/SA00'
#path_predict = './0711/Y/gong/SA/SA2475-80/SA00'
n = 400
x_predict = get_real_data(path_predict,n)
print x_predict.shape

(10001,)


In [41]:
a = x_predict.values

In [43]:
a[index_sel].shape

(1000,)

In [1]:
import tensorflow as tf